server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: seguridad-svc
          uri: ${URI_SEGURIDAD:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: clientes-svc
          uri: ${URI_CLIENTES:http://localhost:8082}
          predicates:
            - Path=/clientes/**
        - id: productos-svc
          uri: ${URI_PRODUCTOS:http://localhost:8083}
          predicates:
            - Path=/productos/**
        - id: ventas-svc
          uri: ${URI_VENTAS:http://localhost:8084}
          predicates:
            - Path=/ventas/**

jwt:
  secret: aW52ZW50YWRvLXBvci1sYS1pbnRlbGlnZW5jaWEtYXJ0aWZpY2lhbC1xdWUtZGVtby1zZWNyZXRv
