server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_ventas
    username: user_ventas
    password: password_ventas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
