server:
  port: 8888

spring:
  application:
    name: msrv-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:./config-data}
